/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DeckId = IDL.Nat;
export const Suit = IDL.Variant({
  'Diamonds' : IDL.Null,
  'Hearts' : IDL.Null,
  'Clubs' : IDL.Null,
  'Joker' : IDL.Null,
  'Spades' : IDL.Null,
});
export const Rank = IDL.Variant({
  'Ace' : IDL.Null,
  'Six' : IDL.Null,
  'Ten' : IDL.Null,
  'Two' : IDL.Null,
  'Eight' : IDL.Null,
  'Seven' : IDL.Null,
  'Five' : IDL.Null,
  'Four' : IDL.Null,
  'Jack' : IDL.Null,
  'King' : IDL.Null,
  'Nine' : IDL.Null,
  'Three' : IDL.Null,
  'Joker' : IDL.Null,
  'Queen' : IDL.Null,
});
export const RepSpec = IDL.Variant({
  'Half' : IDL.Null,
  'JokerChallenge' : IDL.Null,
  'Double' : IDL.Null,
  'Fixed' : IDL.Nat,
});
export const CardId = IDL.Nat;
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const SessionId = IDL.Nat;
export const Timestamp = IDL.Int;
export const WorkoutSummary = IDL.Record({
  'startTime' : Timestamp,
  'totalCards' : IDL.Nat,
  'completedCards' : IDL.Nat,
  'durationSeconds' : IDL.Nat,
  'sessionId' : SessionId,
  'estimatedCalories' : IDL.Nat,
});
export const CardCount = IDL.Variant({
  'Ten' : IDL.Null,
  'FullDeck' : IDL.Null,
  'Twenty' : IDL.Null,
});
export const AchievementId = IDL.Text;
export const AchievementRarity = IDL.Variant({
  'Epic' : IDL.Null,
  'Rare' : IDL.Null,
  'Uncommon' : IDL.Null,
  'Legendary' : IDL.Null,
  'Common' : IDL.Null,
});
export const Achievement = IDL.Record({
  'id' : AchievementId,
  'unlockedAt' : IDL.Opt(IDL.Int),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'rarity' : AchievementRarity,
});
export const UserTier = IDL.Variant({
  'Guest' : IDL.Null,
  'Subscriber' : IDL.Null,
  'Registered' : IDL.Null,
});
export const AdminUserEntry = IDL.Record({
  'principal' : IDL.Principal,
  'tier' : UserTier,
  'email' : IDL.Opt(IDL.Text),
  'isIndefinite' : IDL.Bool,
  'tierExpiresAt' : IDL.Opt(IDL.Int),
});
export const Result_1 = IDL.Variant({
  'ok' : IDL.Vec(AdminUserEntry),
  'err' : IDL.Text,
});
export const Card = IDL.Record({
  'id' : CardId,
  'rank' : Rank,
  'suit' : Suit,
  'exercise' : IDL.Text,
  'deckId' : DeckId,
  'imageUrl' : IDL.Text,
  'repSpec' : RepSpec,
  'videoUrl' : IDL.Text,
});
export const Deck = IDL.Record({
  'id' : DeckId,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'cardCount' : IDL.Nat,
});
export const DeckWithCards = IDL.Record({
  'cards' : IDL.Vec(Card),
  'deck' : Deck,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'aceCardsDrawn' : IDL.Nat,
  'emailVerified' : IDL.Bool,
  'username' : IDL.Text,
  'unlockedAchievements' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int)),
  'createdAt' : IDL.Int,
  'totalWorkouts' : IDL.Nat,
  'totalReps' : IDL.Nat,
  'email' : IDL.Text,
  'totalCalories' : IDL.Nat,
  'kingCardsDrawn' : IDL.Nat,
  'lastWorkoutDate' : IDL.Opt(IDL.Int),
  'totalRepsPerSuit' : IDL.Record({
    'diamonds' : IDL.Nat,
    'clubs' : IDL.Nat,
    'spades' : IDL.Nat,
    'hearts' : IDL.Nat,
  }),
  'longestStreak' : IDL.Nat,
  'fullDecksCompleted' : IDL.Nat,
  'currentStreak' : IDL.Nat,
  'jokerCardsDrawn' : IDL.Nat,
});
export const WorkoutHistoryEntry = IDL.Record({
  'id' : IDL.Text,
  'completedAt' : IDL.Int,
  'aceCardsDrawn' : IDL.Nat,
  'userId' : IDL.Principal,
  'deckId' : IDL.Text,
  'totalReps' : IDL.Nat,
  'kingCardsDrawn' : IDL.Nat,
  'durationSeconds' : IDL.Nat,
  'cardsCompleted' : IDL.Nat,
  'caloriesBurned' : IDL.Nat,
  'repsBySuit' : IDL.Record({
    'diamonds' : IDL.Nat,
    'clubs' : IDL.Nat,
    'spades' : IDL.Nat,
    'hearts' : IDL.Nat,
  }),
  'jokerCardsDrawn' : IDL.Nat,
});
export const OnboardingData = IDL.Record({
  'level' : IDL.Text,
  'gender' : IDL.Text,
  'hasCompletedOnboarding' : IDL.Bool,
});
export const SessionStatus = IDL.Variant({
  'Active' : IDL.Null,
  'Completed' : IDL.Null,
});
export const WorkoutSessionView = IDL.Record({
  'id' : SessionId,
  'currentIndex' : IDL.Nat,
  'startTime' : Timestamp,
  'status' : SessionStatus,
  'totalCards' : IDL.Nat,
  'deckId' : DeckId,
  'cardCount' : IDL.Nat,
  'elapsedSeconds' : IDL.Nat,
  'remainingCards' : IDL.Nat,
  'estimatedCalories' : IDL.Nat,
});
export const JokerChallenge = IDL.Variant({ 'DeadHang30' : IDL.Null });
export const SessionCard = IDL.Record({
  'challenge' : IDL.Opt(JokerChallenge),
  'card' : Card,
  'reps' : IDL.Nat,
  'isMod' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addCard' : IDL.Func(
      [DeckId, Suit, Rank, IDL.Text, RepSpec, IDL.Text, IDL.Text],
      [CardId],
      [],
    ),
  'addDeck' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [DeckId], []),
  'adminGrantSubscriber' : IDL.Func(
      [IDL.Principal, IDL.Opt(IDL.Int), IDL.Bool],
      [Result],
      [],
    ),
  'adminRevokeSubscriber' : IDL.Func([IDL.Principal], [Result], []),
  'completeWorkout' : IDL.Func([SessionId], [IDL.Opt(WorkoutSummary)], []),
  'createWorkoutSession' : IDL.Func([DeckId, CardCount], [SessionId], []),
  'deleteDeck' : IDL.Func([DeckId], [], []),
  'getAchievements' : IDL.Func([], [IDL.Vec(Achievement)], ['query']),
  'getAdminUserList' : IDL.Func([], [Result_1], []),
  'getDeck' : IDL.Func([DeckId], [IDL.Opt(DeckWithCards)], ['query']),
  'getDecks' : IDL.Func([], [IDL.Vec(Deck)], ['query']),
  'getMyProfile' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
      ['query'],
    ),
  'getMyWorkoutHistory' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(WorkoutHistoryEntry), 'err' : IDL.Text })],
      ['query'],
    ),
  'getOnboarding' : IDL.Func([], [IDL.Opt(OnboardingData)], ['query']),
  'getTier' : IDL.Func([IDL.Principal], [UserTier], ['query']),
  'getUserAchievements' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int))],
      ['query'],
    ),
  'getWorkoutSession' : IDL.Func(
      [SessionId],
      [IDL.Opt(WorkoutSessionView)],
      ['query'],
    ),
  'loginUser' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
      [],
    ),
  'nextCard' : IDL.Func([SessionId], [IDL.Opt(SessionCard)], []),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'requestPasswordReset' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'resendVerificationEmail' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'resetPassword' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'revokeTier' : IDL.Func([IDL.Principal], [Result], []),
  'saveOnboarding' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'saveWorkoutHistory' : IDL.Func(
      [WorkoutHistoryEntry],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setAdminPrincipal' : IDL.Func([IDL.Principal], [Result], []),
  'setTier' : IDL.Func(
      [IDL.Principal, UserTier, IDL.Opt(IDL.Int), IDL.Bool],
      [Result],
      [],
    ),
  'updateCard' : IDL.Func(
      [CardId, IDL.Text, RepSpec, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'verifyEmail' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DeckId = IDL.Nat;
  const Suit = IDL.Variant({
    'Diamonds' : IDL.Null,
    'Hearts' : IDL.Null,
    'Clubs' : IDL.Null,
    'Joker' : IDL.Null,
    'Spades' : IDL.Null,
  });
  const Rank = IDL.Variant({
    'Ace' : IDL.Null,
    'Six' : IDL.Null,
    'Ten' : IDL.Null,
    'Two' : IDL.Null,
    'Eight' : IDL.Null,
    'Seven' : IDL.Null,
    'Five' : IDL.Null,
    'Four' : IDL.Null,
    'Jack' : IDL.Null,
    'King' : IDL.Null,
    'Nine' : IDL.Null,
    'Three' : IDL.Null,
    'Joker' : IDL.Null,
    'Queen' : IDL.Null,
  });
  const RepSpec = IDL.Variant({
    'Half' : IDL.Null,
    'JokerChallenge' : IDL.Null,
    'Double' : IDL.Null,
    'Fixed' : IDL.Nat,
  });
  const CardId = IDL.Nat;
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const SessionId = IDL.Nat;
  const Timestamp = IDL.Int;
  const WorkoutSummary = IDL.Record({
    'startTime' : Timestamp,
    'totalCards' : IDL.Nat,
    'completedCards' : IDL.Nat,
    'durationSeconds' : IDL.Nat,
    'sessionId' : SessionId,
    'estimatedCalories' : IDL.Nat,
  });
  const CardCount = IDL.Variant({
    'Ten' : IDL.Null,
    'FullDeck' : IDL.Null,
    'Twenty' : IDL.Null,
  });
  const AchievementId = IDL.Text;
  const AchievementRarity = IDL.Variant({
    'Epic' : IDL.Null,
    'Rare' : IDL.Null,
    'Uncommon' : IDL.Null,
    'Legendary' : IDL.Null,
    'Common' : IDL.Null,
  });
  const Achievement = IDL.Record({
    'id' : AchievementId,
    'unlockedAt' : IDL.Opt(IDL.Int),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'rarity' : AchievementRarity,
  });
  const UserTier = IDL.Variant({
    'Guest' : IDL.Null,
    'Subscriber' : IDL.Null,
    'Registered' : IDL.Null,
  });
  const AdminUserEntry = IDL.Record({
    'principal' : IDL.Principal,
    'tier' : UserTier,
    'email' : IDL.Opt(IDL.Text),
    'isIndefinite' : IDL.Bool,
    'tierExpiresAt' : IDL.Opt(IDL.Int),
  });
  const Result_1 = IDL.Variant({
    'ok' : IDL.Vec(AdminUserEntry),
    'err' : IDL.Text,
  });
  const Card = IDL.Record({
    'id' : CardId,
    'rank' : Rank,
    'suit' : Suit,
    'exercise' : IDL.Text,
    'deckId' : DeckId,
    'imageUrl' : IDL.Text,
    'repSpec' : RepSpec,
    'videoUrl' : IDL.Text,
  });
  const Deck = IDL.Record({
    'id' : DeckId,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'cardCount' : IDL.Nat,
  });
  const DeckWithCards = IDL.Record({ 'cards' : IDL.Vec(Card), 'deck' : Deck });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'aceCardsDrawn' : IDL.Nat,
    'emailVerified' : IDL.Bool,
    'username' : IDL.Text,
    'unlockedAchievements' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int)),
    'createdAt' : IDL.Int,
    'totalWorkouts' : IDL.Nat,
    'totalReps' : IDL.Nat,
    'email' : IDL.Text,
    'totalCalories' : IDL.Nat,
    'kingCardsDrawn' : IDL.Nat,
    'lastWorkoutDate' : IDL.Opt(IDL.Int),
    'totalRepsPerSuit' : IDL.Record({
      'diamonds' : IDL.Nat,
      'clubs' : IDL.Nat,
      'spades' : IDL.Nat,
      'hearts' : IDL.Nat,
    }),
    'longestStreak' : IDL.Nat,
    'fullDecksCompleted' : IDL.Nat,
    'currentStreak' : IDL.Nat,
    'jokerCardsDrawn' : IDL.Nat,
  });
  const WorkoutHistoryEntry = IDL.Record({
    'id' : IDL.Text,
    'completedAt' : IDL.Int,
    'aceCardsDrawn' : IDL.Nat,
    'userId' : IDL.Principal,
    'deckId' : IDL.Text,
    'totalReps' : IDL.Nat,
    'kingCardsDrawn' : IDL.Nat,
    'durationSeconds' : IDL.Nat,
    'cardsCompleted' : IDL.Nat,
    'caloriesBurned' : IDL.Nat,
    'repsBySuit' : IDL.Record({
      'diamonds' : IDL.Nat,
      'clubs' : IDL.Nat,
      'spades' : IDL.Nat,
      'hearts' : IDL.Nat,
    }),
    'jokerCardsDrawn' : IDL.Nat,
  });
  const OnboardingData = IDL.Record({
    'level' : IDL.Text,
    'gender' : IDL.Text,
    'hasCompletedOnboarding' : IDL.Bool,
  });
  const SessionStatus = IDL.Variant({
    'Active' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const WorkoutSessionView = IDL.Record({
    'id' : SessionId,
    'currentIndex' : IDL.Nat,
    'startTime' : Timestamp,
    'status' : SessionStatus,
    'totalCards' : IDL.Nat,
    'deckId' : DeckId,
    'cardCount' : IDL.Nat,
    'elapsedSeconds' : IDL.Nat,
    'remainingCards' : IDL.Nat,
    'estimatedCalories' : IDL.Nat,
  });
  const JokerChallenge = IDL.Variant({ 'DeadHang30' : IDL.Null });
  const SessionCard = IDL.Record({
    'challenge' : IDL.Opt(JokerChallenge),
    'card' : Card,
    'reps' : IDL.Nat,
    'isMod' : IDL.Bool,
  });
  
  return IDL.Service({
    'addCard' : IDL.Func(
        [DeckId, Suit, Rank, IDL.Text, RepSpec, IDL.Text, IDL.Text],
        [CardId],
        [],
      ),
    'addDeck' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [DeckId], []),
    'adminGrantSubscriber' : IDL.Func(
        [IDL.Principal, IDL.Opt(IDL.Int), IDL.Bool],
        [Result],
        [],
      ),
    'adminRevokeSubscriber' : IDL.Func([IDL.Principal], [Result], []),
    'completeWorkout' : IDL.Func([SessionId], [IDL.Opt(WorkoutSummary)], []),
    'createWorkoutSession' : IDL.Func([DeckId, CardCount], [SessionId], []),
    'deleteDeck' : IDL.Func([DeckId], [], []),
    'getAchievements' : IDL.Func([], [IDL.Vec(Achievement)], ['query']),
    'getAdminUserList' : IDL.Func([], [Result_1], []),
    'getDeck' : IDL.Func([DeckId], [IDL.Opt(DeckWithCards)], ['query']),
    'getDecks' : IDL.Func([], [IDL.Vec(Deck)], ['query']),
    'getMyProfile' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
        ['query'],
      ),
    'getMyWorkoutHistory' : IDL.Func(
        [],
        [
          IDL.Variant({
            'ok' : IDL.Vec(WorkoutHistoryEntry),
            'err' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getOnboarding' : IDL.Func([], [IDL.Opt(OnboardingData)], ['query']),
    'getTier' : IDL.Func([IDL.Principal], [UserTier], ['query']),
    'getUserAchievements' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int))],
        ['query'],
      ),
    'getWorkoutSession' : IDL.Func(
        [SessionId],
        [IDL.Opt(WorkoutSessionView)],
        ['query'],
      ),
    'loginUser' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
        [],
      ),
    'nextCard' : IDL.Func([SessionId], [IDL.Opt(SessionCard)], []),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'requestPasswordReset' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'resendVerificationEmail' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'resetPassword' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'revokeTier' : IDL.Func([IDL.Principal], [Result], []),
    'saveOnboarding' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'saveWorkoutHistory' : IDL.Func(
        [WorkoutHistoryEntry],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setAdminPrincipal' : IDL.Func([IDL.Principal], [Result], []),
    'setTier' : IDL.Func(
        [IDL.Principal, UserTier, IDL.Opt(IDL.Int), IDL.Bool],
        [Result],
        [],
      ),
    'updateCard' : IDL.Func(
        [CardId, IDL.Text, RepSpec, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'verifyEmail' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };