/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Achievement {
  'id' : AchievementId,
  'unlockedAt' : [] | [bigint],
  'name' : string,
  'description' : string,
  'rarity' : AchievementRarity,
}
export type AchievementId = string;
export type AchievementRarity = { 'Epic' : null } |
  { 'Rare' : null } |
  { 'Uncommon' : null } |
  { 'Legendary' : null } |
  { 'Common' : null };
export interface AdminUserEntry {
  'principal' : Principal,
  'tier' : UserTier,
  'email' : [] | [string],
  'isIndefinite' : boolean,
  'tierExpiresAt' : [] | [bigint],
}
export interface Card {
  'id' : CardId,
  'rank' : Rank,
  'suit' : Suit,
  'exercise' : string,
  'deckId' : DeckId,
  'imageUrl' : string,
  'repSpec' : RepSpec,
  'videoUrl' : string,
}
export type CardCount = { 'Ten' : null } |
  { 'FullDeck' : null } |
  { 'Twenty' : null };
export type CardId = bigint;
export interface Deck {
  'id' : DeckId,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'cardCount' : bigint,
}
export type DeckId = bigint;
export interface DeckWithCards { 'cards' : Array<Card>, 'deck' : Deck }
export type JokerChallenge = { 'DeadHang30' : null };
export interface OnboardingData {
  'level' : string,
  'gender' : string,
  'hasCompletedOnboarding' : boolean,
}
export type Rank = { 'Ace' : null } |
  { 'Six' : null } |
  { 'Ten' : null } |
  { 'Two' : null } |
  { 'Eight' : null } |
  { 'Seven' : null } |
  { 'Five' : null } |
  { 'Four' : null } |
  { 'Jack' : null } |
  { 'King' : null } |
  { 'Nine' : null } |
  { 'Three' : null } |
  { 'Joker' : null } |
  { 'Queen' : null };
export type RepSpec = { 'Half' : null } |
  { 'JokerChallenge' : null } |
  { 'Double' : null } |
  { 'Fixed' : bigint };
export type Result = { 'ok' : null } |
  { 'err' : string };
export type Result_1 = { 'ok' : Array<AdminUserEntry> } |
  { 'err' : string };
export interface SessionCard {
  'challenge' : [] | [JokerChallenge],
  'card' : Card,
  'reps' : bigint,
  'isMod' : boolean,
}
export type SessionId = bigint;
export type SessionStatus = { 'Active' : null } |
  { 'Completed' : null };
export type Suit = { 'Diamonds' : null } |
  { 'Hearts' : null } |
  { 'Clubs' : null } |
  { 'Joker' : null } |
  { 'Spades' : null };
export type Timestamp = bigint;
export interface UserProfile {
  'principal' : Principal,
  'aceCardsDrawn' : bigint,
  'emailVerified' : boolean,
  'username' : string,
  'unlockedAchievements' : Array<[string, bigint]>,
  'createdAt' : bigint,
  'totalWorkouts' : bigint,
  'totalReps' : bigint,
  'email' : string,
  'totalCalories' : bigint,
  'kingCardsDrawn' : bigint,
  'lastWorkoutDate' : [] | [bigint],
  'totalRepsPerSuit' : {
    'diamonds' : bigint,
    'clubs' : bigint,
    'spades' : bigint,
    'hearts' : bigint,
  },
  'longestStreak' : bigint,
  'fullDecksCompleted' : bigint,
  'currentStreak' : bigint,
  'jokerCardsDrawn' : bigint,
}
export type UserTier = { 'Guest' : null } |
  { 'Subscriber' : null } |
  { 'Registered' : null };
export interface WorkoutHistoryEntry {
  'id' : string,
  'completedAt' : bigint,
  'aceCardsDrawn' : bigint,
  'userId' : Principal,
  'deckId' : string,
  'totalReps' : bigint,
  'kingCardsDrawn' : bigint,
  'durationSeconds' : bigint,
  'cardsCompleted' : bigint,
  'caloriesBurned' : bigint,
  'repsBySuit' : {
    'diamonds' : bigint,
    'clubs' : bigint,
    'spades' : bigint,
    'hearts' : bigint,
  },
  'jokerCardsDrawn' : bigint,
}
export interface WorkoutSessionView {
  'id' : SessionId,
  'currentIndex' : bigint,
  'startTime' : Timestamp,
  'status' : SessionStatus,
  'totalCards' : bigint,
  'deckId' : DeckId,
  'cardCount' : bigint,
  'elapsedSeconds' : bigint,
  'remainingCards' : bigint,
  'estimatedCalories' : bigint,
}
export interface WorkoutSummary {
  'startTime' : Timestamp,
  'totalCards' : bigint,
  'completedCards' : bigint,
  'durationSeconds' : bigint,
  'sessionId' : SessionId,
  'estimatedCalories' : bigint,
}
export interface _SERVICE {
  'addCard' : ActorMethod<
    [DeckId, Suit, Rank, string, RepSpec, string, string],
    CardId
  >,
  'addDeck' : ActorMethod<[string, string, boolean], DeckId>,
  'adminGrantSubscriber' : ActorMethod<
    [Principal, [] | [bigint], boolean],
    Result
  >,
  'adminRevokeSubscriber' : ActorMethod<[Principal], Result>,
  'completeWorkout' : ActorMethod<[SessionId], [] | [WorkoutSummary]>,
  'createWorkoutSession' : ActorMethod<[DeckId, CardCount], SessionId>,
  'deleteDeck' : ActorMethod<[DeckId], undefined>,
  'getAchievements' : ActorMethod<[], Array<Achievement>>,
  'getAdminUserList' : ActorMethod<[], Result_1>,
  'getDeck' : ActorMethod<[DeckId], [] | [DeckWithCards]>,
  'getDecks' : ActorMethod<[], Array<Deck>>,
  'getMyProfile' : ActorMethod<[], { 'ok' : UserProfile } | { 'err' : string }>,
  'getMyWorkoutHistory' : ActorMethod<
    [],
    { 'ok' : Array<WorkoutHistoryEntry> } |
      { 'err' : string }
  >,
  'getOnboarding' : ActorMethod<[], [] | [OnboardingData]>,
  'getTier' : ActorMethod<[Principal], UserTier>,
  'getUserAchievements' : ActorMethod<[], Array<[string, bigint]>>,
  'getWorkoutSession' : ActorMethod<[SessionId], [] | [WorkoutSessionView]>,
  'loginUser' : ActorMethod<
    [string, string],
    { 'ok' : UserProfile } |
      { 'err' : string }
  >,
  'nextCard' : ActorMethod<[SessionId], [] | [SessionCard]>,
  'registerUser' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'requestPasswordReset' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'resendVerificationEmail' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'resetPassword' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'revokeTier' : ActorMethod<[Principal], Result>,
  'saveOnboarding' : ActorMethod<[string, string], Result>,
  'saveWorkoutHistory' : ActorMethod<
    [WorkoutHistoryEntry],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setAdminPrincipal' : ActorMethod<[Principal], Result>,
  'setTier' : ActorMethod<
    [Principal, UserTier, [] | [bigint], boolean],
    Result
  >,
  'updateCard' : ActorMethod<
    [CardId, string, RepSpec, string, string],
    undefined
  >,
  'updateProfile' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'verifyEmail' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];