/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface OnboardingData {
    level: string;
    gender: string;
    hasCompletedOnboarding: boolean;
}
export type DeckId = bigint;
export type Timestamp = bigint;
export type CardId = bigint;
export interface Card {
    id: CardId;
    rank: Rank;
    suit: Suit;
    exercise: string;
    deckId: DeckId;
    imageUrl: string;
    repSpec: RepSpec;
    videoUrl: string;
}
export type RepSpec = {
    __kind__: "Half";
    Half: null;
} | {
    __kind__: "JokerChallenge";
    JokerChallenge: null;
} | {
    __kind__: "Double";
    Double: null;
} | {
    __kind__: "Fixed";
    Fixed: bigint;
};
export type SessionId = bigint;
export interface DeckWithCards {
    cards: Array<Card>;
    deck: Deck;
}
export interface AdminUserEntry {
    principal: Principal;
    tier: UserTier;
    email?: string;
    isIndefinite: boolean;
    tierExpiresAt?: bigint;
}
export type Result_1 = {
    __kind__: "ok";
    ok: Array<AdminUserEntry>;
} | {
    __kind__: "err";
    err: string;
};
export interface SessionCard {
    challenge?: JokerChallenge;
    card: Card;
    reps: bigint;
    isMod: boolean;
}
export interface Achievement {
    id: AchievementId;
    unlockedAt?: bigint;
    name: string;
    description: string;
    rarity: AchievementRarity;
}
export interface WorkoutSessionView {
    id: SessionId;
    currentIndex: bigint;
    startTime: Timestamp;
    status: SessionStatus;
    totalCards: bigint;
    deckId: DeckId;
    cardCount: bigint;
    elapsedSeconds: bigint;
    remainingCards: bigint;
    estimatedCalories: bigint;
}
export interface WorkoutSummary {
    startTime: Timestamp;
    totalCards: bigint;
    completedCards: bigint;
    durationSeconds: bigint;
    sessionId: SessionId;
    estimatedCalories: bigint;
}
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export type AchievementId = string;
export interface Deck {
    id: DeckId;
    name: string;
    isAvailable: boolean;
    description: string;
    cardCount: bigint;
}
export interface WorkoutHistoryEntry {
    id: string;
    completedAt: bigint;
    aceCardsDrawn: bigint;
    userId: Principal;
    deckId: string;
    totalReps: bigint;
    kingCardsDrawn: bigint;
    durationSeconds: bigint;
    cardsCompleted: bigint;
    caloriesBurned: bigint;
    repsBySuit: {
        diamonds: bigint;
        clubs: bigint;
        spades: bigint;
        hearts: bigint;
    };
    jokerCardsDrawn: bigint;
}
export interface UserProfile {
    principal: Principal;
    aceCardsDrawn: bigint;
    emailVerified: boolean;
    username: string;
    unlockedAchievements: Array<[string, bigint]>;
    createdAt: bigint;
    totalWorkouts: bigint;
    totalReps: bigint;
    email: string;
    totalCalories: bigint;
    kingCardsDrawn: bigint;
    lastWorkoutDate?: bigint;
    totalRepsPerSuit: {
        diamonds: bigint;
        clubs: bigint;
        spades: bigint;
        hearts: bigint;
    };
    longestStreak: bigint;
    fullDecksCompleted: bigint;
    currentStreak: bigint;
    jokerCardsDrawn: bigint;
}
export enum AchievementRarity {
    Epic = "Epic",
    Rare = "Rare",
    Uncommon = "Uncommon",
    Legendary = "Legendary",
    Common = "Common"
}
export enum CardCount {
    Ten = "Ten",
    FullDeck = "FullDeck",
    Twenty = "Twenty"
}
export enum JokerChallenge {
    DeadHang30 = "DeadHang30"
}
export enum Rank {
    Ace = "Ace",
    Six = "Six",
    Ten = "Ten",
    Two = "Two",
    Eight = "Eight",
    Seven = "Seven",
    Five = "Five",
    Four = "Four",
    Jack = "Jack",
    King = "King",
    Nine = "Nine",
    Three = "Three",
    Joker = "Joker",
    Queen = "Queen"
}
export enum SessionStatus {
    Active = "Active",
    Completed = "Completed"
}
export enum Suit {
    Diamonds = "Diamonds",
    Hearts = "Hearts",
    Clubs = "Clubs",
    Joker = "Joker",
    Spades = "Spades"
}
export enum UserTier {
    Guest = "Guest",
    Subscriber = "Subscriber",
    Registered = "Registered"
}
export interface backendInterface {
    addCard(deckId: DeckId, suit: Suit, rank: Rank, exercise: string, repSpec: RepSpec, imageUrl: string, videoUrl: string): Promise<CardId>;
    addDeck(name: string, description: string, isAvailable: boolean): Promise<DeckId>;
    adminGrantSubscriber(targetPrincipal: Principal, expiresAt: bigint | null, isIndefinite: boolean): Promise<Result>;
    adminRevokeSubscriber(targetPrincipal: Principal): Promise<Result>;
    completeWorkout(sessionId: SessionId): Promise<WorkoutSummary | null>;
    createWorkoutSession(deckId: DeckId, cardCount: CardCount): Promise<SessionId>;
    deleteDeck(id: DeckId): Promise<void>;
    getAchievements(): Promise<Array<Achievement>>;
    getAdminUserList(): Promise<Result_1>;
    getDeck(id: DeckId): Promise<DeckWithCards | null>;
    getDecks(): Promise<Array<Deck>>;
    getMyProfile(): Promise<{
        __kind__: "ok";
        ok: UserProfile;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getMyWorkoutHistory(): Promise<{
        __kind__: "ok";
        ok: Array<WorkoutHistoryEntry>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getOnboarding(): Promise<OnboardingData | null>;
    getTier(userId: Principal): Promise<UserTier>;
    getUserAchievements(): Promise<Array<[string, bigint]>>;
    getWorkoutSession(sessionId: SessionId): Promise<WorkoutSessionView | null>;
    loginUser(email: string, passwordHash: string): Promise<{
        __kind__: "ok";
        ok: UserProfile;
    } | {
        __kind__: "err";
        err: string;
    }>;
    nextCard(sessionId: SessionId): Promise<SessionCard | null>;
    registerUser(username: string, email: string, passwordHash: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    requestPasswordReset(email: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    resendVerificationEmail(email: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    resetPassword(token: string, newPasswordHash: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    revokeTier(userId: Principal): Promise<Result>;
    saveOnboarding(gender: string, level: string): Promise<Result>;
    saveWorkoutHistory(entry: WorkoutHistoryEntry): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setAdminPrincipal(newAdmin: Principal): Promise<Result>;
    setTier(userId: Principal, tier: UserTier, expiresAt: bigint | null, isIndefinite: boolean): Promise<Result>;
    updateCard(cardId: CardId, exercise: string, repSpec: RepSpec, imageUrl: string, videoUrl: string): Promise<void>;
    updateProfile(username: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    verifyEmail(token: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { Achievement as _Achievement, AchievementId as _AchievementId, AchievementRarity as _AchievementRarity, AdminUserEntry as _AdminUserEntry, Card as _Card, CardCount as _CardCount, CardId as _CardId, Deck as _Deck, DeckId as _DeckId, DeckWithCards as _DeckWithCards, JokerChallenge as _JokerChallenge, OnboardingData as _OnboardingData, Rank as _Rank, RepSpec as _RepSpec, Result as _Result, Result_1 as _Result_1, SessionCard as _SessionCard, SessionId as _SessionId, SessionStatus as _SessionStatus, Suit as _Suit, Timestamp as _Timestamp, UserProfile as _UserProfile, UserTier as _UserTier, WorkoutHistoryEntry as _WorkoutHistoryEntry, WorkoutSessionView as _WorkoutSessionView, WorkoutSummary as _WorkoutSummary } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCard(arg0: DeckId, arg1: Suit, arg2: Rank, arg3: string, arg4: RepSpec, arg5: string, arg6: string): Promise<CardId> {
        if (this.processError) {
            try {
                const result = await this.actor.addCard(arg0, to_candid_Suit_n1(this._uploadFile, this._downloadFile, arg1), to_candid_Rank_n3(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_RepSpec_n5(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCard(arg0, to_candid_Suit_n1(this._uploadFile, this._downloadFile, arg1), to_candid_Rank_n3(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_RepSpec_n5(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
            return result;
        }
    }
    async addDeck(arg0: string, arg1: string, arg2: boolean): Promise<DeckId> {
        if (this.processError) {
            try {
                const result = await this.actor.addDeck(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDeck(arg0, arg1, arg2);
            return result;
        }
    }
    async adminGrantSubscriber(arg0: Principal, arg1: bigint | null, arg2: boolean): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGrantSubscriber(arg0, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGrantSubscriber(arg0, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminRevokeSubscriber(arg0: Principal): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRevokeSubscriber(arg0);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRevokeSubscriber(arg0);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async completeWorkout(arg0: SessionId): Promise<WorkoutSummary | null> {
        if (this.processError) {
            try {
                const result = await this.actor.completeWorkout(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeWorkout(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async createWorkoutSession(arg0: DeckId, arg1: CardCount): Promise<SessionId> {
        if (this.processError) {
            try {
                const result = await this.actor.createWorkoutSession(arg0, to_candid_CardCount_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWorkoutSession(arg0, to_candid_CardCount_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteDeck(arg0: DeckId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDeck(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDeck(arg0);
            return result;
        }
    }
    async getAchievements(): Promise<Array<Achievement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAchievements();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAchievements();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminUserList(): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminUserList();
                return from_candid_Result_1_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminUserList();
            return from_candid_Result_1_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDeck(arg0: DeckId): Promise<DeckWithCards | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeck(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeck(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDecks(): Promise<Array<Deck>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDecks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDecks();
            return result;
        }
    }
    async getMyProfile(): Promise<{
        __kind__: "ok";
        ok: UserProfile;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_variant_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_variant_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyWorkoutHistory(): Promise<{
        __kind__: "ok";
        ok: Array<WorkoutHistoryEntry>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyWorkoutHistory();
                return from_candid_variant_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyWorkoutHistory();
            return from_candid_variant_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOnboarding(): Promise<OnboardingData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOnboarding();
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOnboarding();
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTier(arg0: Principal): Promise<UserTier> {
        if (this.processError) {
            try {
                const result = await this.actor.getTier(arg0);
                return from_candid_UserTier_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTier(arg0);
            return from_candid_UserTier_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserAchievements(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserAchievements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserAchievements();
            return result;
        }
    }
    async getWorkoutSession(arg0: SessionId): Promise<WorkoutSessionView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutSession(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutSession(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async loginUser(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: UserProfile;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.loginUser(arg0, arg1);
                return from_candid_variant_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginUser(arg0, arg1);
            return from_candid_variant_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async nextCard(arg0: SessionId): Promise<SessionCard | null> {
        if (this.processError) {
            try {
                const result = await this.actor.nextCard(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.nextCard(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2);
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2);
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestPasswordReset(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.requestPasswordReset(arg0);
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestPasswordReset(arg0);
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async resendVerificationEmail(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.resendVerificationEmail(arg0);
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resendVerificationEmail(arg0);
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async resetPassword(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.resetPassword(arg0, arg1);
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetPassword(arg0, arg1);
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async revokeTier(arg0: Principal): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeTier(arg0);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeTier(arg0);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveOnboarding(arg0: string, arg1: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.saveOnboarding(arg0, arg1);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveOnboarding(arg0, arg1);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveWorkoutHistory(arg0: WorkoutHistoryEntry): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.saveWorkoutHistory(arg0);
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveWorkoutHistory(arg0);
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async setAdminPrincipal(arg0: Principal): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdminPrincipal(arg0);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdminPrincipal(arg0);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async setTier(arg0: Principal, arg1: UserTier, arg2: bigint | null, arg3: boolean): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.setTier(arg0, to_candid_UserTier_n55(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTier(arg0, to_candid_UserTier_n55(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCard(arg0: CardId, arg1: string, arg2: RepSpec, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCard(arg0, arg1, to_candid_RepSpec_n5(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCard(arg0, arg1, to_candid_RepSpec_n5(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async updateProfile(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0);
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0);
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyEmail(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyEmail(arg0);
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyEmail(arg0);
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AchievementRarity_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AchievementRarity): AchievementRarity {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Achievement_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Achievement): Achievement {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_AdminUserEntry_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminUserEntry): AdminUserEntry {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Card_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Card): Card {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_DeckWithCards_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeckWithCards): DeckWithCards {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_JokerChallenge_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JokerChallenge): JokerChallenge {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_Rank_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Rank): Rank {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_RepSpec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RepSpec): RepSpec {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_SessionCard_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionCard): SessionCard {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_SessionStatus_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionStatus): SessionStatus {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_Suit_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Suit): Suit {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_UserTier_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserTier): UserTier {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_WorkoutSessionView_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkoutSessionView): WorkoutSessionView {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WorkoutSummary]): WorkoutSummary | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DeckWithCards]): DeckWithCards | null {
    return value.length === 0 ? null : from_candid_DeckWithCards_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OnboardingData]): OnboardingData | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WorkoutSessionView]): WorkoutSessionView | null {
    return value.length === 0 ? null : from_candid_WorkoutSessionView_n45(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SessionCard]): SessionCard | null {
    return value.length === 0 ? null : from_candid_SessionCard_n50(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JokerChallenge]): JokerChallenge | null {
    return value.length === 0 ? null : from_candid_JokerChallenge_n53(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AchievementId;
    unlockedAt: [] | [bigint];
    name: string;
    description: string;
    rarity: _AchievementRarity;
}): {
    id: AchievementId;
    unlockedAt?: bigint;
    name: string;
    description: string;
    rarity: AchievementRarity;
} {
    return {
        id: value.id,
        unlockedAt: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.unlockedAt)),
        name: value.name,
        description: value.description,
        rarity: from_candid_AchievementRarity_n17(_uploadFile, _downloadFile, value.rarity)
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    tier: _UserTier;
    email: [] | [string];
    isIndefinite: boolean;
    tierExpiresAt: [] | [bigint];
}): {
    principal: Principal;
    tier: UserTier;
    email?: string;
    isIndefinite: boolean;
    tierExpiresAt?: bigint;
} {
    return {
        principal: value.principal,
        tier: from_candid_UserTier_n24(_uploadFile, _downloadFile, value.tier),
        email: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.email)),
        isIndefinite: value.isIndefinite,
        tierExpiresAt: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.tierExpiresAt))
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cards: Array<_Card>;
    deck: _Deck;
}): {
    cards: Array<Card>;
    deck: Deck;
} {
    return {
        cards: from_candid_vec_n30(_uploadFile, _downloadFile, value.cards),
        deck: value.deck
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CardId;
    rank: _Rank;
    suit: _Suit;
    exercise: string;
    deckId: _DeckId;
    imageUrl: string;
    repSpec: _RepSpec;
    videoUrl: string;
}): {
    id: CardId;
    rank: Rank;
    suit: Suit;
    exercise: string;
    deckId: DeckId;
    imageUrl: string;
    repSpec: RepSpec;
    videoUrl: string;
} {
    return {
        id: value.id,
        rank: from_candid_Rank_n33(_uploadFile, _downloadFile, value.rank),
        suit: from_candid_Suit_n35(_uploadFile, _downloadFile, value.suit),
        exercise: value.exercise,
        deckId: value.deckId,
        imageUrl: value.imageUrl,
        repSpec: from_candid_RepSpec_n37(_uploadFile, _downloadFile, value.repSpec),
        videoUrl: value.videoUrl
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    aceCardsDrawn: bigint;
    emailVerified: boolean;
    username: string;
    unlockedAchievements: Array<[string, bigint]>;
    createdAt: bigint;
    totalWorkouts: bigint;
    totalReps: bigint;
    email: string;
    totalCalories: bigint;
    kingCardsDrawn: bigint;
    lastWorkoutDate: [] | [bigint];
    totalRepsPerSuit: {
        diamonds: bigint;
        clubs: bigint;
        spades: bigint;
        hearts: bigint;
    };
    longestStreak: bigint;
    fullDecksCompleted: bigint;
    currentStreak: bigint;
    jokerCardsDrawn: bigint;
}): {
    principal: Principal;
    aceCardsDrawn: bigint;
    emailVerified: boolean;
    username: string;
    unlockedAchievements: Array<[string, bigint]>;
    createdAt: bigint;
    totalWorkouts: bigint;
    totalReps: bigint;
    email: string;
    totalCalories: bigint;
    kingCardsDrawn: bigint;
    lastWorkoutDate?: bigint;
    totalRepsPerSuit: {
        diamonds: bigint;
        clubs: bigint;
        spades: bigint;
        hearts: bigint;
    };
    longestStreak: bigint;
    fullDecksCompleted: bigint;
    currentStreak: bigint;
    jokerCardsDrawn: bigint;
} {
    return {
        principal: value.principal,
        aceCardsDrawn: value.aceCardsDrawn,
        emailVerified: value.emailVerified,
        username: value.username,
        unlockedAchievements: value.unlockedAchievements,
        createdAt: value.createdAt,
        totalWorkouts: value.totalWorkouts,
        totalReps: value.totalReps,
        email: value.email,
        totalCalories: value.totalCalories,
        kingCardsDrawn: value.kingCardsDrawn,
        lastWorkoutDate: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.lastWorkoutDate)),
        totalRepsPerSuit: value.totalRepsPerSuit,
        longestStreak: value.longestStreak,
        fullDecksCompleted: value.fullDecksCompleted,
        currentStreak: value.currentStreak,
        jokerCardsDrawn: value.jokerCardsDrawn
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SessionId;
    currentIndex: bigint;
    startTime: _Timestamp;
    status: _SessionStatus;
    totalCards: bigint;
    deckId: _DeckId;
    cardCount: bigint;
    elapsedSeconds: bigint;
    remainingCards: bigint;
    estimatedCalories: bigint;
}): {
    id: SessionId;
    currentIndex: bigint;
    startTime: Timestamp;
    status: SessionStatus;
    totalCards: bigint;
    deckId: DeckId;
    cardCount: bigint;
    elapsedSeconds: bigint;
    remainingCards: bigint;
    estimatedCalories: bigint;
} {
    return {
        id: value.id,
        currentIndex: value.currentIndex,
        startTime: value.startTime,
        status: from_candid_SessionStatus_n47(_uploadFile, _downloadFile, value.status),
        totalCards: value.totalCards,
        deckId: value.deckId,
        cardCount: value.cardCount,
        elapsedSeconds: value.elapsedSeconds,
        remainingCards: value.remainingCards,
        estimatedCalories: value.estimatedCalories
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    challenge: [] | [_JokerChallenge];
    card: _Card;
    reps: bigint;
    isMod: boolean;
}): {
    challenge?: JokerChallenge;
    card: Card;
    reps: bigint;
    isMod: boolean;
} {
    return {
        challenge: record_opt_to_undefined(from_candid_opt_n52(_uploadFile, _downloadFile, value.challenge)),
        card: from_candid_Card_n31(_uploadFile, _downloadFile, value.card),
        reps: value.reps,
        isMod: value.isMod
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Epic: null;
} | {
    Rare: null;
} | {
    Uncommon: null;
} | {
    Legendary: null;
} | {
    Common: null;
}): AchievementRarity {
    return "Epic" in value ? AchievementRarity.Epic : "Rare" in value ? AchievementRarity.Rare : "Uncommon" in value ? AchievementRarity.Uncommon : "Legendary" in value ? AchievementRarity.Legendary : "Common" in value ? AchievementRarity.Common : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_AdminUserEntry>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<AdminUserEntry>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n21(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Guest: null;
} | {
    Subscriber: null;
} | {
    Registered: null;
}): UserTier {
    return "Guest" in value ? UserTier.Guest : "Subscriber" in value ? UserTier.Subscriber : "Registered" in value ? UserTier.Registered : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Ace: null;
} | {
    Six: null;
} | {
    Ten: null;
} | {
    Two: null;
} | {
    Eight: null;
} | {
    Seven: null;
} | {
    Five: null;
} | {
    Four: null;
} | {
    Jack: null;
} | {
    King: null;
} | {
    Nine: null;
} | {
    Three: null;
} | {
    Joker: null;
} | {
    Queen: null;
}): Rank {
    return "Ace" in value ? Rank.Ace : "Six" in value ? Rank.Six : "Ten" in value ? Rank.Ten : "Two" in value ? Rank.Two : "Eight" in value ? Rank.Eight : "Seven" in value ? Rank.Seven : "Five" in value ? Rank.Five : "Four" in value ? Rank.Four : "Jack" in value ? Rank.Jack : "King" in value ? Rank.King : "Nine" in value ? Rank.Nine : "Three" in value ? Rank.Three : "Joker" in value ? Rank.Joker : "Queen" in value ? Rank.Queen : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Diamonds: null;
} | {
    Hearts: null;
} | {
    Clubs: null;
} | {
    Joker: null;
} | {
    Spades: null;
}): Suit {
    return "Diamonds" in value ? Suit.Diamonds : "Hearts" in value ? Suit.Hearts : "Clubs" in value ? Suit.Clubs : "Joker" in value ? Suit.Joker : "Spades" in value ? Suit.Spades : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Half: null;
} | {
    JokerChallenge: null;
} | {
    Double: null;
} | {
    Fixed: bigint;
}): {
    __kind__: "Half";
    Half: null;
} | {
    __kind__: "JokerChallenge";
    JokerChallenge: null;
} | {
    __kind__: "Double";
    Double: null;
} | {
    __kind__: "Fixed";
    Fixed: bigint;
} {
    return "Half" in value ? {
        __kind__: "Half",
        Half: value.Half
    } : "JokerChallenge" in value ? {
        __kind__: "JokerChallenge",
        JokerChallenge: value.JokerChallenge
    } : "Double" in value ? {
        __kind__: "Double",
        Double: value.Double
    } : "Fixed" in value ? {
        __kind__: "Fixed",
        Fixed: value.Fixed
    } : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserProfile;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserProfile_n40(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_WorkoutHistoryEntry>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<WorkoutHistoryEntry>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Active: null;
} | {
    Completed: null;
}): SessionStatus {
    return "Active" in value ? SessionStatus.Active : "Completed" in value ? SessionStatus.Completed : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    DeadHang30: null;
}): JokerChallenge {
    return "DeadHang30" in value ? JokerChallenge.DeadHang30 : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Achievement>): Array<Achievement> {
    return value.map((x)=>from_candid_Achievement_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdminUserEntry>): Array<AdminUserEntry> {
    return value.map((x)=>from_candid_AdminUserEntry_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Card>): Array<Card> {
    return value.map((x)=>from_candid_Card_n31(_uploadFile, _downloadFile, x));
}
function to_candid_CardCount_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CardCount): _CardCount {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Rank_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Rank): _Rank {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_RepSpec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RepSpec): _RepSpec {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Suit_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Suit): _Suit {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserTier_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserTier): _UserTier {
    return to_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CardCount): {
    Ten: null;
} | {
    FullDeck: null;
} | {
    Twenty: null;
} {
    return value == CardCount.Ten ? {
        Ten: null
    } : value == CardCount.FullDeck ? {
        FullDeck: null
    } : value == CardCount.Twenty ? {
        Twenty: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Suit): {
    Diamonds: null;
} | {
    Hearts: null;
} | {
    Clubs: null;
} | {
    Joker: null;
} | {
    Spades: null;
} {
    return value == Suit.Diamonds ? {
        Diamonds: null
    } : value == Suit.Hearts ? {
        Hearts: null
    } : value == Suit.Clubs ? {
        Clubs: null
    } : value == Suit.Joker ? {
        Joker: null
    } : value == Suit.Spades ? {
        Spades: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Rank): {
    Ace: null;
} | {
    Six: null;
} | {
    Ten: null;
} | {
    Two: null;
} | {
    Eight: null;
} | {
    Seven: null;
} | {
    Five: null;
} | {
    Four: null;
} | {
    Jack: null;
} | {
    King: null;
} | {
    Nine: null;
} | {
    Three: null;
} | {
    Joker: null;
} | {
    Queen: null;
} {
    return value == Rank.Ace ? {
        Ace: null
    } : value == Rank.Six ? {
        Six: null
    } : value == Rank.Ten ? {
        Ten: null
    } : value == Rank.Two ? {
        Two: null
    } : value == Rank.Eight ? {
        Eight: null
    } : value == Rank.Seven ? {
        Seven: null
    } : value == Rank.Five ? {
        Five: null
    } : value == Rank.Four ? {
        Four: null
    } : value == Rank.Jack ? {
        Jack: null
    } : value == Rank.King ? {
        King: null
    } : value == Rank.Nine ? {
        Nine: null
    } : value == Rank.Three ? {
        Three: null
    } : value == Rank.Joker ? {
        Joker: null
    } : value == Rank.Queen ? {
        Queen: null
    } : value;
}
function to_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserTier): {
    Guest: null;
} | {
    Subscriber: null;
} | {
    Registered: null;
} {
    return value == UserTier.Guest ? {
        Guest: null
    } : value == UserTier.Subscriber ? {
        Subscriber: null
    } : value == UserTier.Registered ? {
        Registered: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "Half";
    Half: null;
} | {
    __kind__: "JokerChallenge";
    JokerChallenge: null;
} | {
    __kind__: "Double";
    Double: null;
} | {
    __kind__: "Fixed";
    Fixed: bigint;
}): {
    Half: null;
} | {
    JokerChallenge: null;
} | {
    Double: null;
} | {
    Fixed: bigint;
} {
    return value.__kind__ === "Half" ? {
        Half: value.Half
    } : value.__kind__ === "JokerChallenge" ? {
        JokerChallenge: value.JokerChallenge
    } : value.__kind__ === "Double" ? {
        Double: value.Double
    } : value.__kind__ === "Fixed" ? {
        Fixed: value.Fixed
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
